### ISSUE TITLE
Official Launch Checklist

### ISSUE THREAD

**Issue by arisac** [newtonproject/newbridge.network#24]
**This checklist should start only Official Launch is planned**

- [x] `Contents` Final Check is completed #28

- [x] `Hugo Config Link` is updated #29

- [x] `CLA Link` is updated #29

- [x] `CNAME file` is updated #29

- [x] `DNS`  is updated

**Comment by arisac** [comment]
#30
